CREATE TABLE example_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    description CLOB,
    age NUMBER,
    price NUMBER(10,2),
    is_active CHAR(1),
    created_at TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    birth_date DATE,
    event_time TIMESTAMP,
    metadata CLOB,
    ip_address VARCHAR2(45),
    user_uuid RAW(16)
);